var domAnimator = new DomAnimator();
    domAnimator.addFrame('Hello');
    domAnimator.addFrame('Il faut bien regarder');
    domAnimator.addFrame('le code source');
    domAnimator.addFrame('Tu découvriras');
    domAnimator.addFrame('Que rien');
    domAnimator.addFrame('est affiché');
    domAnimator.addFrame('par hasard');
    domAnimator.addFrame('Bonjour');
    domAnimator.addFrame('au professeur');
    domAnimator.addFrame('qui');
    domAnimator.addFrame('Fait bien');
    domAnimator.addFrame('son travail');
    domAnimator.addFrame(':)');
    domAnimator.addFrame('Site réalisé grâce');
    domAnimator.addFrame('materialise.css');
    domAnimator.addFrame('domanimator');
    domAnimator.addFrame('jquerry');
    domAnimator.addFrame('o_o');
    domAnimator.addFrame('-_o');
    domAnimator.addFrame('o_o');
    domAnimator.addFrame('-_o');
    domAnimator.addFrame('o_o');
    domAnimator.addFrame('-_o');
    domAnimator.addFrame('o_o');
    domAnimator.addFrame('-_o');
    domAnimator.animate();
    domAnimator.animate(4000); //ms